# Random setup
import random

SEED = 1337
random.seed(SEED)

COLLISION_BLOCK_ID = 32125

VISION_RADIUS = 8
ATTENTION_BANDWIDTH = 8
RETENTION = 8

EMBEDDING_MODEL = "all-MiniLM-L12-v1"
VECTOR_DIMENSION = 384
MAX_TOKENS = 512
