all_arena_addresses = [
    "the Ville:Giorgio Rossi's apartment",
    "the Ville:Giorgio Rossi's apartment:bathroom",
    "the Ville:Carlos Gomez's apartment",
    "the Ville:Carlos Gomez's apartment:bathroom",
    "the Ville:Arthur Burton's apartment",
    "the Ville:Arthur Burton's apartment:main room",
    "the Ville:Arthur Burton's apartment:bathroom",
    "the Ville:Ryan Park's apartment",
    "the Ville:Ryan Park's apartment:bathroom",
    "the Ville:Isabella Rodriguez's apartment",
    "the Ville:Isabella Rodriguez's apartment:main room",
    "the Ville:Isabella Rodriguez's apartment:bathroom",
    "the Ville:Giorgio Rossi's apartment:bathroom:shower",
    "the Ville:Giorgio Rossi's apartment:bathroom:bathroom sink",
    "the Ville:Giorgio Rossi's apartment:bathroom:toilet",
    "the Ville:Carlos Gomez's apartment:bathroom:shower",
    "the Ville:Carlos Gomez's apartment:bathroom:bathroom sink",
    "the Ville:Carlos Gomez's apartment:bathroom:toilet",
    "the Ville:Arthur Burton's apartment:main room:bed",
    "<spawn_loc>sp-A",
    "<spawn_loc>sp-B",
    "the Ville:Arthur Burton's apartment:main room:refrigerator",
    "the Ville:Arthur Burton's apartment:main room:closet",
    "the Ville:Arthur Burton's apartment:main room:shelf",
    "the Ville:Arthur Burton's apartment:bathroom:shower",
    "the Ville:Arthur Burton's apartment:bathroom:toilet",
    "the Ville:Ryan Park's apartment:bathroom:shower",
    "the Ville:Ryan Park's apartment:bathroom:bathroom sink",
    "the Ville:Ryan Park's apartment:bathroom:toilet",
    "the Ville:Isabella Rodriguez's apartment:main room:bed",
    "the Ville:Isabella Rodriguez's apartment:main room:refrigerator",
    "the Ville:Isabella Rodriguez's apartment:main room:closet",
    "the Ville:Isabella Rodriguez's apartment:main room:shelf",
    "the Ville:Isabella Rodriguez's apartment:bathroom:shower",
    "the Ville:Isabella Rodriguez's apartment:bathroom:toilet",
    "the Ville:Arthur Burton's apartment:main room:guitar",
    "the Ville:Arthur Burton's apartment:bathroom:bathroom sink",
    "the Ville:Isabella Rodriguez's apartment:main room:desk",
    "the Ville:Isabella Rodriguez's apartment:bathroom:bathroom sink",
    "the Ville:artist's co-living space",
    "the Ville:artist's co-living space:Latoya Williams's room",
    "the Ville:artist's co-living space:Latoya Williams's bathroom",
    "the Ville:artist's co-living space:Rajiv Patel's room",
    "the Ville:artist's co-living space:Rajiv Patel's bathroom",
    "the Ville:artist's co-living space:Abigail Chen's room",
    "the Ville:Arthur Burton's apartment:main room:desk",
    "the Ville:Hobbs Cafe",
    "the Ville:Giorgio Rossi's apartment:main room",
    "the Ville:Carlos Gomez's apartment:main room",
    "the Ville:artist's co-living space:Latoya Williams's room:bed",
    "the Ville:artist's co-living space:Latoya Williams's bathroom:shower",
    "the Ville:artist's co-living space:Latoya Williams's bathroom:toilet",
    "the Ville:artist's co-living space:Rajiv Patel's room:bed",
    "the Ville:artist's co-living space:Rajiv Patel's bathroom:shower",
    "the Ville:artist's co-living space:Rajiv Patel's bathroom:toilet",
    "the Ville:artist's co-living space:Abigail Chen's room:bed",
    "the Ville:artist's co-living space:Abigail Chen's room:closet",
    "the Ville:The Rose and Crown Pub",
    "the Ville:Ryan Park's apartment:main room",
    "the Ville:Giorgio Rossi's apartment:main room:bed",
    "the Ville:Giorgio Rossi's apartment:main room:refrigerator",
    "the Ville:Carlos Gomez's apartment:main room:bed",
    "the Ville:Carlos Gomez's apartment:main room:refrigerator",
    "the Ville:artist's co-living space:Latoya Williams's room:closet",
    "the Ville:artist's co-living space:Rajiv Patel's room:closet",
    "the Ville:Ryan Park's apartment:main room:bed",
    "the Ville:Ryan Park's apartment:main room:refrigerator",
    "the Ville:Hobbs Cafe:cafe",
    "the Ville:Hobbs Cafe:cafe:refrigerator",
    "the Ville:Hobbs Cafe:cafe:cooking area",
    "the Ville:Hobbs Cafe:cafe:kitchen sink",
    "the Ville:Hobbs Cafe:cafe:behind the cafe counter",
    "the Ville:Oak Hill College",
    "the Ville:Oak Hill College:classroom",
    "the Ville:Oak Hill College:library",
    "the Ville:artist's co-living space:Latoya Williams's room:desk",
    "the Ville:artist's co-living space:Abigail Chen's bathroom",
    "the Ville:The Rose and Crown Pub:pub",
    "the Ville:The Rose and Crown Pub:pub:refrigerator",
    "the Ville:The Rose and Crown Pub:pub:behind the bar counter",
    "the Ville:The Rose and Crown Pub:pub:kitchen sink",
    "the Ville:The Rose and Crown Pub:pub:cooking area",
    "the Ville:Giorgio Rossi's apartment:main room:cooking area",
    "the Ville:Carlos Gomez's apartment:main room:cooking area",
    "the Ville:Oak Hill College:classroom:blackboard",
    "the Ville:Oak Hill College:library:library sofa",
    "the Ville:Oak Hill College:library:bookshelf",
    "the Ville:artist's co-living space:Latoya Williams's room:shelf",
    "the Ville:artist's co-living space:Latoya Williams's bathroom:bathroom sink",
    "the Ville:artist's co-living space:Rajiv Patel's room:guitar",
    "the Ville:artist's co-living space:Rajiv Patel's bathroom:bathroom sink",
    "the Ville:artist's co-living space:Abigail Chen's bathroom:bathroom sink",
    "the Ville:artist's co-living space:Abigail Chen's bathroom:toilet",
    "the Ville:artist's co-living space:Abigail Chen's bathroom:shower",
    "the Ville:Ryan Park's apartment:main room:cooking area",
    "the Ville:Hobbs Cafe:cafe:cafe customer seating",
    "the Ville:Giorgio Rossi's apartment:main room:desk",
    "the Ville:Giorgio Rossi's apartment:main room:kitchen sink",
    "the Ville:Carlos Gomez's apartment:main room:desk",
    "the Ville:Carlos Gomez's apartment:main room:kitchen sink",
    "the Ville:Oak Hill College:classroom:classroom student seating",
    "the Ville:artist's co-living space:Rajiv Patel's room:easel",
    "the Ville:artist's co-living space:Abigail Chen's room:desk",
    "the Ville:Ryan Park's apartment:main room:kitchen sink",
    "the Ville:Oak Hill College:library:library table",
    "the Ville:The Rose and Crown Pub:pub:bar customer seating",
    "the Ville:Giorgio Rossi's apartment:main room:closet",
    "the Ville:Carlos Gomez's apartment:main room:closet",
    "the Ville:Oak Hill College:classroom:classroom podium",
    "the Ville:Ryan Park's apartment:main room:computer desk",
    "the Ville:Ryan Park's apartment:main room:closet",
    "the Ville:Giorgio Rossi's apartment:main room:blackboard",
    "the Ville:artist's co-living space:kitchen",
    "the Ville:artist's co-living space:kitchen:refrigerator",
    "the Ville:artist's co-living space:kitchen:toaster",
    "the Ville:artist's co-living space:kitchen:kitchen sink",
    "the Ville:The Rose and Crown Pub:pub:shelf",
    "the Ville:The Rose and Crown Pub:pub:microphone",
    "the Ville:artist's co-living space:common room",
    "the Ville:artist's co-living space:kitchen:cooking area",
    "the Ville:Hobbs Cafe:cafe:piano",
    "the Ville:artist's co-living space:Francisco Lopez's room",
    "the Ville:artist's co-living space:Francisco Lopez's bathroom",
    "the Ville:artist's co-living space:Hailey Johnson's room",
    "the Ville:artist's co-living space:Hailey Johnson's bathroom",
    "the Ville:artist's co-living space:Francisco Lopez's room:shelf",
    "the Ville:artist's co-living space:Francisco Lopez's bathroom:toilet",
    "the Ville:artist's co-living space:Hailey Johnson's room:easel",
    "the Ville:artist's co-living space:Hailey Johnson's bathroom:toilet",
    "the Ville:artist's co-living space:common room:common room table",
    "the Ville:artist's co-living space:Francisco Lopez's room:closet",
    "the Ville:artist's co-living space:Francisco Lopez's bathroom:bathroom sink",
    "the Ville:artist's co-living space:Hailey Johnson's room:closet",
    "the Ville:artist's co-living space:Hailey Johnson's bathroom:bathroom sink",
    "the Ville:artist's co-living space:Hailey Johnson's room:desk",
    "the Ville:artist's co-living space:common room:common room sofa",
    "the Ville:Oak Hill College:hallway",
    "the Ville:artist's co-living space:Francisco Lopez's room:easel",
    "the Ville:Dorm for Oak Hill College",
    "the Ville:Dorm for Oak Hill College:garden",
    "the Ville:Dorm for Oak Hill College:garden:dorm garden",
    "the Ville:artist's co-living space:Francisco Lopez's room:bed",
    "the Ville:artist's co-living space:Francisco Lopez's bathroom:shower",
    "the Ville:artist's co-living space:Hailey Johnson's room:bed",
    "the Ville:artist's co-living space:Hailey Johnson's bathroom:shower",
    "the Ville:Johnson Park",
    "the Ville:Johnson Park:park",
    "the Ville:Johnson Park:park:park garden",
    "the Ville:Harvey Oak Supply Store",
    "the Ville:Harvey Oak Supply Store:supply store",
    "the Ville:The Willows Market and Pharmacy",
    "the Ville:The Willows Market and Pharmacy:store",
    "the Ville:Harvey Oak Supply Store:supply store:supply store product shelf",
    "the Ville:Harvey Oak Supply Store:supply store:behind the supply store counter",
    "the Ville:The Willows Market and Pharmacy:store:behind the grocery counter",
    "the Ville:Dorm for Oak Hill College:Klaus Mueller's room",
    "the Ville:The Willows Market and Pharmacy:store:pharmacy store shelf",
    "the Ville:Dorm for Oak Hill College:kitchen",
    "the Ville:Dorm for Oak Hill College:kitchen:toaster",
    "the Ville:Dorm for Oak Hill College:kitchen:kitchen sink",
    "the Ville:Dorm for Oak Hill College:kitchen:refrigerator",
    "the Ville:Dorm for Oak Hill College:Klaus Mueller's room:closet",
    "the Ville:Harvey Oak Supply Store:supply store:supply store counter",
    "the Ville:The Willows Market and Pharmacy:store:grocery store counter",
    "the Ville:Dorm for Oak Hill College:common room",
    "the Ville:Dorm for Oak Hill College:kitchen:cooking area",
    "the Ville:Dorm for Oak Hill College:Klaus Mueller's room:bed",
    "the Ville:Dorm for Oak Hill College:Klaus Mueller's room:game console",
    "the Ville:Dorm for Oak Hill College:Klaus Mueller's room:desk",
    "the Ville:Dorm for Oak Hill College:common room:common room table",
    "the Ville:The Willows Market and Pharmacy:store:grocery store shelf",
    "the Ville:Dorm for Oak Hill College:man's bathroom",
    "the Ville:Dorm for Oak Hill College:man's bathroom:shower",
    "the Ville:Dorm for Oak Hill College:man's bathroom:bathroom sink",
    "the Ville:Dorm for Oak Hill College:man's bathroom:toilet",
    "the Ville:Dorm for Oak Hill College:common room:common room sofa",
    "the Ville:The Willows Market and Pharmacy:store:behind the pharmacy counter",
    "the Ville:The Willows Market and Pharmacy:store:pharmacy store counter",
    "the Ville:Dorm for Oak Hill College:common room:pool table",
    "the Ville:Dorm for Oak Hill College:woman's bathroom",
    "the Ville:Dorm for Oak Hill College:Maria Lopez's room",
    "the Ville:Dorm for Oak Hill College:woman's bathroom:toilet",
    "the Ville:Dorm for Oak Hill College:woman's bathroom:bathroom sink",
    "the Ville:Dorm for Oak Hill College:Maria Lopez's room:closet",
    "the Ville:Dorm for Oak Hill College:Maria Lopez's room:computer",
    "the Ville:Dorm for Oak Hill College:Maria Lopez's room:desk",
    "the Ville:Dorm for Oak Hill College:Wolfgang Schulz's room",
    "the Ville:Dorm for Oak Hill College:Ayesha Khan's room",
    "the Ville:Dorm for Oak Hill College:Maria Lopez's room:blackboard",
    "the Ville:Dorm for Oak Hill College:Wolfgang Schulz's room:desk",
    "the Ville:Dorm for Oak Hill College:Ayesha Khan's room:shelf",
    "the Ville:Dorm for Oak Hill College:Ayesha Khan's room:desk",
    "the Ville:Dorm for Oak Hill College:Maria Lopez's room:bed",
    "the Ville:Dorm for Oak Hill College:woman's bathroom:shower",
    "the Ville:Adam Smith's house",
    "the Ville:Adam Smith's house:main room",
    "the Ville:Yuriko Yamamoto's house",
    "the Ville:Yuriko Yamamoto's house:main room",
    "the Ville:Moore family's house",
    "the Ville:Moore family's house:main room",
    "the Ville:Dorm for Oak Hill College:Wolfgang Schulz's room:lifting weight",
    "the Ville:Adam Smith's house:main room:closet",
    "the Ville:Yuriko Yamamoto's house:main room:desk",
    "the Ville:Yuriko Yamamoto's house:main room:closet",
    "the Ville:Moore family's house:main room:closet",
    "the Ville:Moore family's house:main room:common room sofa",
    "the Ville:Dorm for Oak Hill College:Wolfgang Schulz's room:closet",
    "the Ville:Dorm for Oak Hill College:Ayesha Khan's room:closet",
    "the Ville:Adam Smith's house:main room:cooking area",
    "the Ville:Yuriko Yamamoto's house:main room:cooking area",
    "the Ville:Moore family's house:main room:desk",
    "the Ville:Moore family's house:main room:cooking area",
    "the Ville:Dorm for Oak Hill College:Wolfgang Schulz's room:game console",
    "the Ville:Dorm for Oak Hill College:Ayesha Khan's room:bed",
    "the Ville:Adam Smith's house:main room:desk",
    "the Ville:Adam Smith's house:main room:kitchen sink",
    "the Ville:Yuriko Yamamoto's house:main room:shelf",
    "the Ville:Yuriko Yamamoto's house:main room:kitchen sink",
    "the Ville:Moore family's house:main room:kitchen sink",
    "the Ville:Dorm for Oak Hill College:Wolfgang Schulz's room:bed",
    "the Ville:Tamara Taylor and Carmen Ortiz's house",
    "the Ville:Moreno family's house",
    "the Ville:Lin family's house",
    "the Ville:Adam Smith's house:main room:bed",
    "the Ville:Adam Smith's house:main room:refrigerator",
    "the Ville:Yuriko Yamamoto's house:main room:bed",
    "the Ville:Yuriko Yamamoto's house:main room:refrigerator",
    "the Ville:Moore family's house:main room:bed",
    "the Ville:Moore family's house:main room:refrigerator",
    "the Ville:Tamara Taylor and Carmen Ortiz's house:common room",
    "the Ville:Tamara Taylor and Carmen Ortiz's house:common room:shelf",
    "the Ville:Tamara Taylor and Carmen Ortiz's house:kitchen",
    "the Ville:Tamara Taylor and Carmen Ortiz's house:kitchen:kitchen sink",
    "the Ville:Tamara Taylor and Carmen Ortiz's house:bathroom",
    "the Ville:Tamara Taylor and Carmen Ortiz's house:bathroom:toilet",
    "the Ville:Tamara Taylor and Carmen Ortiz's house:bathroom:bathroom sink",
    "the Ville:Moreno family's house:common room",
    "the Ville:Moreno family's house:common room:shelf",
    "the Ville:Moreno family's house:kitchen",
    "the Ville:Moreno family's house:kitchen:kitchen sink",
    "the Ville:Moreno family's house:bathroom",
    "the Ville:Moreno family's house:bathroom:toilet",
    "the Ville:Moreno family's house:bathroom:bathroom sink",
    "the Ville:Lin family's house:common room",
    "the Ville:Lin family's house:common room:shelf",
    "the Ville:Lin family's house:kitchen",
    "the Ville:Lin family's house:kitchen:kitchen sink",
    "the Ville:Lin family's house:bathroom",
    "the Ville:Lin family's house:bathroom:toilet",
    "the Ville:Lin family's house:bathroom:bathroom sink",
    "the Ville:Adam Smith's house:bathroom",
    "the Ville:Yuriko Yamamoto's house:bathroom",
    "the Ville:Moore family's house:bathroom",
    "the Ville:Tamara Taylor and Carmen Ortiz's house:kitchen:cooking area",
    "the Ville:Moreno family's house:common room:harp",
    "the Ville:Moreno family's house:kitchen:cooking area",
    "the Ville:Lin family's house:kitchen:cooking area",
    "the Ville:Tamara Taylor and Carmen Ortiz's house:common room:common room table",
    "the Ville:Tamara Taylor and Carmen Ortiz's house:bathroom:shower",
    "the Ville:Moreno family's house:common room:common room table",
    "the Ville:Moreno family's house:bathroom:shower",
    "the Ville:Lin family's house:common room:common room table",
    "the Ville:Lin family's house:bathroom:shower",
    "the Ville:Adam Smith's house:bathroom:bathroom sink",
    "the Ville:Adam Smith's house:bathroom:toilet",
    "the Ville:Yuriko Yamamoto's house:bathroom:bathroom sink",
    "the Ville:Yuriko Yamamoto's house:bathroom:toilet",
    "the Ville:Moore family's house:bathroom:bathroom sink",
    "the Ville:Moore family's house:bathroom:toilet",
    "the Ville:Tamara Taylor and Carmen Ortiz's house:kitchen:refrigerator",
    "the Ville:Moreno family's house:kitchen:refrigerator",
    "the Ville:Lin family's house:kitchen:refrigerator",
    "the Ville:Adam Smith's house:bathroom:shower",
    "the Ville:Yuriko Yamamoto's house:bathroom:shower",
    "the Ville:Moore family's house:bathroom:shower",
    "the Ville:Tamara Taylor and Carmen Ortiz's house:Tamara Taylor's room",
    "the Ville:Tamara Taylor and Carmen Ortiz's house:Tamara Taylor's room:closet",
    "the Ville:Tamara Taylor and Carmen Ortiz's house:Carmen Ortiz's room",
    "the Ville:Moreno family's house:Tom and Jane Moreno's bedroom",
    "the Ville:Moreno family's house:Tom and Jane Moreno's bedroom:closet",
    "the Ville:Moreno family's house:empty bedroom",
    "the Ville:Lin family's house:Mei and John Lin's bedroom",
    "the Ville:Lin family's house:Mei and John Lin's bedroom:closet",
    "the Ville:Lin family's house:Eddy Lin's bedroom",
    "the Ville:Lin family's house:Eddy Lin's bedroom:closet",
    "the Ville:Tamara Taylor and Carmen Ortiz's house:Tamara Taylor's room:desk",
    "the Ville:Tamara Taylor and Carmen Ortiz's house:Tamara Taylor's room:bed",
    "the Ville:Tamara Taylor and Carmen Ortiz's house:Carmen Ortiz's room:bed",
    "the Ville:Tamara Taylor and Carmen Ortiz's house:Carmen Ortiz's room:closet",
    "the Ville:Moreno family's house:Tom and Jane Moreno's bedroom:desk",
    "the Ville:Moreno family's house:Tom and Jane Moreno's bedroom:bed",
    "the Ville:Moreno family's house:empty bedroom:bed",
    "the Ville:Moreno family's house:empty bedroom:closet",
    "the Ville:Lin family's house:Mei and John Lin's bedroom:desk",
    "the Ville:Lin family's house:Mei and John Lin's bedroom:bed",
    "the Ville:Lin family's house:Eddy Lin's bedroom:bed",
    "the Ville:Lin family's house:Eddy Lin's bedroom:desk",
    "the Ville:Tamara Taylor and Carmen Ortiz's house:Carmen Ortiz's room:guitar",
    "the Ville:Moreno family's house:empty bedroom:guitar",
    "the Ville:Tamara Taylor and Carmen Ortiz's house:garden",
    "the Ville:Tamara Taylor and Carmen Ortiz's house:garden:house garden",
    "the Ville:Moreno family's house:garden",
    "the Ville:Moreno family's house:garden:house garden",
    "the Ville:Lin family's house:garden",
    "the Ville:Lin family's house:garden:house garden",
    "the Ville:Moreno family's house:garden:garden chair",
]

public_arena_addresses = [
    "<spawn_loc>sp-A",
    "<spawn_loc>sp-B",
    "the Ville:artist's co-living space",
    "the Ville:Hobbs Cafe",
    "the Ville:The Rose and Crown Pub",
    "the Ville:Hobbs Cafe:cafe",
    "the Ville:Hobbs Cafe:cafe:refrigerator",
    "the Ville:Hobbs Cafe:cafe:cooking area",
    "the Ville:Hobbs Cafe:cafe:kitchen sink",
    "the Ville:Hobbs Cafe:cafe:behind the cafe counter",
    "the Ville:Oak Hill College",
    "the Ville:Oak Hill College:library",
    "the Ville:The Rose and Crown Pub:pub",
    "the Ville:The Rose and Crown Pub:pub:refrigerator",
    "the Ville:The Rose and Crown Pub:pub:behind the bar counter",
    "the Ville:The Rose and Crown Pub:pub:kitchen sink",
    "the Ville:The Rose and Crown Pub:pub:cooking area",
    "the Ville:Oak Hill College:library:library sofa",
    "the Ville:Oak Hill College:library:bookshelf",
    "the Ville:Hobbs Cafe:cafe:cafe customer seating",
    "the Ville:Oak Hill College:library:library table",
    "the Ville:The Rose and Crown Pub:pub:bar customer seating",
    "the Ville:artist's co-living space:kitchen",
    "the Ville:artist's co-living space:kitchen:refrigerator",
    "the Ville:artist's co-living space:kitchen:toaster",
    "the Ville:artist's co-living space:kitchen:kitchen sink",
    "the Ville:The Rose and Crown Pub:pub:shelf",
    "the Ville:The Rose and Crown Pub:pub:microphone",
    "the Ville:artist's co-living space:kitchen:cooking area",
    "the Ville:Hobbs Cafe:cafe:piano",
    "the Ville:Oak Hill College:hallway",
    "the Ville:Johnson Park",
    "the Ville:Johnson Park:park",
    "the Ville:Johnson Park:park:park garden",
    "the Ville:Harvey Oak Supply Store",
    "the Ville:Harvey Oak Supply Store:supply store",
    "the Ville:The Willows Market and Pharmacy",
    "the Ville:The Willows Market and Pharmacy:store",
    "the Ville:Harvey Oak Supply Store:supply store:supply store product shelf",
    "the Ville:Harvey Oak Supply Store:supply store:behind the supply store counter",
    "the Ville:The Willows Market and Pharmacy:store:behind the grocery counter",
    "the Ville:The Willows Market and Pharmacy:store:pharmacy store shelf",
    "the Ville:Harvey Oak Supply Store:supply store:supply store counter",
    "the Ville:The Willows Market and Pharmacy:store:grocery store counter",
    "the Ville:The Willows Market and Pharmacy:store:grocery store shelf",
    "the Ville:The Willows Market and Pharmacy:store:behind the pharmacy counter",
    "the Ville:The Willows Market and Pharmacy:store:pharmacy store counter",
]

meeting_addresses = [
    "the Ville:Harvey Oak Supply Store",
    "the Ville:Harvey Oak Supply Store:supply store",
    "the Ville:The Willows Market and Pharmacy",
    "the Ville:The Willows Market and Pharmacy:store",
    "the Ville:Harvey Oak Supply Store:supply store:supply store product shelf",
    "the Ville:Harvey Oak Supply Store:supply store:behind the supply store counter",
    "the Ville:The Willows Market and Pharmacy:store:behind the grocery counter",
    "the Ville:The Willows Market and Pharmacy:store:pharmacy store shelf",
    "the Ville:Harvey Oak Supply Store:supply store:supply store counter",
    "the Ville:The Willows Market and Pharmacy:store:grocery store counter",
    "the Ville:The Willows Market and Pharmacy:store:grocery store shelf",
    "the Ville:The Willows Market and Pharmacy:store:behind the pharmacy counter",
    "the Ville:The Willows Market and Pharmacy:store:pharmacy store counter",
]

college_addresses = [
    "the Ville:Oak Hill College",
    "the Ville:Oak Hill College:library",
    "the Ville:Oak Hill College:library:library sofa",
    "the Ville:Oak Hill College:library:bookshelf",
    "the Ville:Oak Hill College:library:library table",
    "the Ville:Oak Hill College:hallway",
]
