# Generated by Django 5.0.1 on 2024-01-10 13:25

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Simulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("movement", "Movement"),
                            ("thought", "Thought"),
                            ("occurence", "Occurence"),
                            ("chat", "Chat"),
                            ("action", "Action"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "position_x",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "position_y",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                ("sim_time_created", models.DateTimeField(blank=True, null=True)),
                ("sim_time_expiration", models.DateTimeField(blank=True, null=True)),
                ("sim_time_last_accessed", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("poignancy", models.FloatField(blank=True, null=True)),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                ("predicate", models.CharField(blank=True, max_length=255, null=True)),
                ("object", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="agents.agent",
                    ),
                ),
                (
                    "simulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="simulations.simulation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
