# Generated by Django 5.0.1 on 2024-01-09 23:16

from django.db import migrations


def create_first_simulation(apps, schema_editor):
    Simulation = apps.get_model("simulations", "Simulation")

    Simulation.objects.create(name="Prime")


def revert_first_simulation(apps, schema_editor):
    Simulation = apps.get_model("simulations", "Simulation")

    Simulation.objects.get(id=1).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("simulations", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_first_simulation, revert_first_simulation),
    ]
