# Generated by Django 5.0.1 on 2024-01-10 13:31

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("simulations", "0003_auto_20240110_1330"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="embedding",
            field=pgvector.django.VectorField(dimensions=384, null=True),
        ),
    ]
