# Generated by Django 5.0.1 on 2024-01-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simulations", "0004_event_embedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="poignancy",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
