# Generated by Django 5.0.1 on 2024-01-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simulations", "0005_alter_event_poignancy"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulation",
            name="step",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
