# Generated by Django 5.0.1 on 2024-01-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simulations", "0007_event_address_event_interacting_with_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulation",
            name="step",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
