# Generated by Django 5.0.1 on 2024-01-20 01:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("simulations", "0008_alter_simulation_step"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="interacting_with",
            new_name="interact_with",
        ),
    ]
