# Generated by Django 5.0.1 on 2024-01-22 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0013_alter_actionplan_type"),
        ("simulations", "0009_rename_interacting_with_event_interact_with"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="interact_with",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interact_with",
                to="agents.agent",
            ),
        ),
    ]
