# Generated by Django 5.0.1 on 2024-01-05 11:49

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("sprite_name", models.CharField(max_length=50)),
                (
                    "curr_position_x",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "curr_position_y",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                ("last_position_x", models.PositiveIntegerField(blank=True, null=True)),
                ("last_position_y", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "unique_together": {("name", "sprite_name")},
            },
        ),
    ]
