# Generated by Django 5.0.1 on 2024-01-03 22:49
from django.db import migrations


def convert_to_sprite_name(name):
    return name.replace(" ", "_")


def load_agent_data(apps, schema_editor):
    Agent = apps.get_model("agents", "Agent")

    agent_data = [
        "Abigail Chen",
        "Adam Smith",
        "Arthur Burton",
        "Ayesha Khan",
        "Carlos Gomez",
        "Carmen Ortiz",
        "Eddy Lin",
        "Francisco Lopez",
        "Giorgio Rossi",
        "Hailey Johnson",
        "Isabella Rodriguez",
        "Jane Moreno",
        "Jennifer Moore",
        "John Lin",
        "Klaus Mueller",
        "Latoya Williams",
        "Maria Lopez",
        "Mei Lin",
        "Rajiv Patel",
        "Ryan Park",
        "Sam Moore",
        "Tamara Taylor",
        "Tom Moreno",
        "Wolfgang Schulz",
        "Yuriko Yamamoto",
    ]
    for name in agent_data:
        sprite_name = convert_to_sprite_name(name)
        Agent.objects.create(
            name=name, sprite_name=sprite_name, curr_position_x=68, curr_position_y=58
        )


def revert_load_agent_data(apps, schema_editor):
    Agent = apps.get_model("agents", "Agent")
    Agent.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_agent_data, revert_load_agent_data),
    ]
