# Generated by Django 5.0.1 on 2024-01-15 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0003_auto_20240110_1326"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("duration", models.PositiveIntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("pronunciatio", models.TextField(blank=True, null=True)),
                ("chat", models.TextField(blank=True, null=True)),
                (
                    "chatting_with_buffer",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("chatting_end_time", models.DateTimeField(blank=True, null=True)),
                ("planned_path", models.JSONField(blank=True, default=list, null=True)),
                (
                    "chatting_with",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan",
                        to="agents.agent",
                    ),
                ),
            ],
        ),
    ]
