# Generated by Django 5.0.1 on 2024-01-16 11:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0004_actionplan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actionplan",
            name="chatting_with",
        ),
    ]
