# Generated by Django 5.0.1 on 2024-01-16 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0005_remove_actionplan_chatting_with"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="chatting_with",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="agents.agent",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="plan",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent",
                to="agents.actionplan",
            ),
        ),
    ]
