# Generated by Django 5.0.1 on 2024-01-20 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0008_actionplan_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actionplan",
            name="chatting_end_time",
        ),
        migrations.RemoveField(
            model_name="actionplan",
            name="chatting_with_buffer",
        ),
        migrations.AddField(
            model_name="actionplan",
            name="interact_with",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="agents.agent",
            ),
        ),
    ]
