# Generated by Django 5.0.1 on 2024-01-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0009_remove_actionplan_chatting_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionplan",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("wait", "Wait"),
                    ("move", "Move"),
                    ("chat_with", "Chat with"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
