# Generated by Django 5.0.1 on 2024-01-20 19:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0010_alter_actionplan_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="chatting_with",
        ),
    ]
