# Generated by Django 5.0.1 on 2024-01-21 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0011_remove_agent_chatting_with"),
        ("simulations", "0009_rename_interacting_with_event_interact_with"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionplan",
            name="simulation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_plans",
                to="simulations.simulation",
            ),
        ),
    ]
