# Generated by Django 5.0.1 on 2024-01-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0012_actionplan_simulation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionplan",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("wait", "Wait"),
                    ("move", "Move"),
                    ("chat_move", "Chat move"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
